# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

try:
    from . import sglang_lite_pb2 as sglang__lite__pb2
except ImportError:
    import sglang_lite_pb2 as sglang__lite__pb2

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in sglang_lite_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class HealthStub:
    """Note: This is the authoritative proto for sglang-lite <-> unigateway gRPC.
    Extended for tools support to match unigateway client skeleton.
    Health service (standard)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
            "/sglang_lite.Health/Check",
            request_serializer=sglang__lite__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=sglang__lite__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.Watch = channel.unary_stream(
            "/sglang_lite.Health/Watch",
            request_serializer=sglang__lite__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=sglang__lite__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class HealthServicer:
    """Note: This is the authoritative proto for sglang-lite <-> unigateway gRPC.
    Extended for tools support to match unigateway client skeleton.
    Health service (standard)
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Check": grpc.unary_unary_rpc_method_handler(
            servicer.Check,
            request_deserializer=sglang__lite__pb2.HealthCheckRequest.FromString,
            response_serializer=sglang__lite__pb2.HealthCheckResponse.SerializeToString,
        ),
        "Watch": grpc.unary_stream_rpc_method_handler(
            servicer.Watch,
            request_deserializer=sglang__lite__pb2.HealthCheckRequest.FromString,
            response_serializer=sglang__lite__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sglang_lite.Health", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("sglang_lite.Health", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Health:
    """Note: This is the authoritative proto for sglang-lite <-> unigateway gRPC.
    Extended for tools support to match unigateway client skeleton.
    Health service (standard)
    """

    @staticmethod
    def Check(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sglang_lite.Health/Check",
            sglang__lite__pb2.HealthCheckRequest.SerializeToString,
            sglang__lite__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Watch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/sglang_lite.Health/Watch",
            sglang__lite__pb2.HealthCheckRequest.SerializeToString,
            sglang__lite__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class SglangLiteServiceStub:
    """Main service for compatibility with OpenAI surface"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletions = channel.unary_unary(
            "/sglang_lite.SglangLiteService/ChatCompletions",
            request_serializer=sglang__lite__pb2.ChatCompletionsRequest.SerializeToString,
            response_deserializer=sglang__lite__pb2.ChatCompletionsResponse.FromString,
            _registered_method=True,
        )
        self.ChatCompletionsStream = channel.unary_stream(
            "/sglang_lite.SglangLiteService/ChatCompletionsStream",
            request_serializer=sglang__lite__pb2.ChatCompletionsRequest.SerializeToString,
            response_deserializer=sglang__lite__pb2.ChatCompletionChunk.FromString,
            _registered_method=True,
        )
        self.Embeddings = channel.unary_unary(
            "/sglang_lite.SglangLiteService/Embeddings",
            request_serializer=sglang__lite__pb2.EmbeddingsRequest.SerializeToString,
            response_deserializer=sglang__lite__pb2.EmbeddingsResponse.FromString,
            _registered_method=True,
        )
        self.ListModels = channel.unary_unary(
            "/sglang_lite.SglangLiteService/ListModels",
            request_serializer=sglang__lite__pb2.Empty.SerializeToString,
            response_deserializer=sglang__lite__pb2.ListModelsResponse.FromString,
            _registered_method=True,
        )


class SglangLiteServiceServicer:
    """Main service for compatibility with OpenAI surface"""

    def ChatCompletions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChatCompletionsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Embeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SglangLiteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ChatCompletions": grpc.unary_unary_rpc_method_handler(
            servicer.ChatCompletions,
            request_deserializer=sglang__lite__pb2.ChatCompletionsRequest.FromString,
            response_serializer=sglang__lite__pb2.ChatCompletionsResponse.SerializeToString,
        ),
        "ChatCompletionsStream": grpc.unary_stream_rpc_method_handler(
            servicer.ChatCompletionsStream,
            request_deserializer=sglang__lite__pb2.ChatCompletionsRequest.FromString,
            response_serializer=sglang__lite__pb2.ChatCompletionChunk.SerializeToString,
        ),
        "Embeddings": grpc.unary_unary_rpc_method_handler(
            servicer.Embeddings,
            request_deserializer=sglang__lite__pb2.EmbeddingsRequest.FromString,
            response_serializer=sglang__lite__pb2.EmbeddingsResponse.SerializeToString,
        ),
        "ListModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListModels,
            request_deserializer=sglang__lite__pb2.Empty.FromString,
            response_serializer=sglang__lite__pb2.ListModelsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sglang_lite.SglangLiteService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("sglang_lite.SglangLiteService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SglangLiteService:
    """Main service for compatibility with OpenAI surface"""

    @staticmethod
    def ChatCompletions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sglang_lite.SglangLiteService/ChatCompletions",
            sglang__lite__pb2.ChatCompletionsRequest.SerializeToString,
            sglang__lite__pb2.ChatCompletionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChatCompletionsStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/sglang_lite.SglangLiteService/ChatCompletionsStream",
            sglang__lite__pb2.ChatCompletionsRequest.SerializeToString,
            sglang__lite__pb2.ChatCompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Embeddings(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sglang_lite.SglangLiteService/Embeddings",
            sglang__lite__pb2.EmbeddingsRequest.SerializeToString,
            sglang__lite__pb2.EmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sglang_lite.SglangLiteService/ListModels",
            sglang__lite__pb2.Empty.SerializeToString,
            sglang__lite__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
